# Generated by Django 3.2.8 on 2022-08-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='alt',
            field=models.CharField(default='essa', max_length=100),
            preserve_default=False,
        ),
    ]
